spring:
  profiles:
    active: dev
  http:
    encoding:
      charset: utf-8
  thymeleaf:
    mode: LEGACYHTML5 #非严格的html5

#服务器级设置
server:
  session-timeout: 1800
#    tomcat:
#        max-threads: 1000
#        min-spare-threads: 30
  port: 80
  uri-encoding: utf-8
  servlet:
    context-path: /
#  ssl:
#    key-store:
#    key-password:
#    key-store-type:
#    key-alias:

#配置缓存和session存储方式，默认ehcache,可选redis
cacheType: ehcache