spring:
  profiles:
    active: dev
  http:
    encoding:
      charset: utf-8

#服务器级设置
server:
  session-timeout: 1800
#    tomcat:
#        max-threads: 1000
#        min-spare-threads: 30
  port: 8080
  uri-encoding: utf-8

#配置缓存和session存储方式，默认ehcache,可选redis
cacheType: ehcache