package com.terrydr.common.dao;

/**
 * Copyright (C), 2018-2020, NanJing Terrydr. Co., Ltd.
 *
 * @Package: com.terrydr.common.dao
 * @Description: ${TODO}
 * @author: YanZhengYuan
 * @Date: 2018/4/17 10:54
 * @version: 1.00
 */
public interface EntityDAO<T> {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu
     *
     * @mbg.generated
     */
    int insert(T t);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu
     *
     * @mbg.generated
     */
    int insertSelective(T t);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu
     *
     * @mbg.generated
     */
    T selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(T t);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(T t);

}
